# Generated by Django 3.2.15 on 2022-08-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201118_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='relation_posts',
            field=models.ManyToManyField(blank=True, related_name='_blog_post_relation_posts_+', to='blog.Post', verbose_name='関連記事'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.Tag', verbose_name='タグ'),
        ),
    ]
